spring.application.name=auth-service
spring.datasource.url=jdbc:postgresql://localhost:5432/kanbanic_auth
spring.datasource.username=postgres
spring.datasource.password=kanbanic123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=kanbanicSuperSecretKeyForJWTSigningChangeThisLater123456
jwt.expiration-ms=3600000